language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t multiform/docker-react -f Dockerfile .

script:
  - docker run -e CI=true multiform/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-228889253310"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY